services:
  medusa:
    profiles:
      - dev
    build:
      target: deps
    container_name: medusa_backend_dev
    environment:
      NODE_ENV: development
      PORT: 9000
    working_dir: /server/apps/backend
    command: pnpm dev
    ports:
      - "9000:9000"
      - "5173:5173"
    volumes:
      - .:/server
      - /server/node_modules
      - /server/apps/backend/node_modules

  storefront:
    profiles:
      - dev
    build:
      target: deps
    container_name: medusa_storefront_dev
    environment:
      NODE_ENV: development
      PORT: 8000
      WATCHPACK_POLLING: "true"
    working_dir: /server/apps/storefront
    command: pnpm dev
    ports:
      - "8000:8000"
    volumes:
      - .:/server
      - /server/node_modules
      - /server/apps/storefront/node_modules
      - /server/apps/storefront/.next
